on:
  push:
    tags:
      - 'v*'  # Trigger this workflow on tag push, e.g., v1.0.0, v2.0.0
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: threeal/cmake-action@v2.1.0

      - name: Build the project
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests (optional)
        run: |
          cd build
          ctest --output-on-failure

  package:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Define platforms for packaging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up CMake
        uses: threeal/cmake-action@v2.1.0

      - name: Generate packages for multiple formats
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
          # Set the CPack generator to include all desired formats for all platforms
          export CPACK_GENERATOR="TGZ;ZIP;RPM;DEB;DNF;NSIS"
          cpack -C Release

      - name: Check if release exists and upload packages
        id: upload
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: build/package/*  # Path to all generated packages
          tag: ${{ github.ref }}  # The version tag
          name: Build and Release  # Name the release as 'Build and Release'
          update: true  # Set this to true to update the existing release if it exists
